### PR TITLE
12 generate pip package

### LINKED ISSUE #12: Generate pip package
I would like simplify the usage of the tool by end user to avoid downloading the zip package.

The solution for this is to generate pip package to run it in the following way:
pip install javacore-analyser
`python -m javacore-analyser --input-data=/tmp/javacores --output-report=/tmp/javacore-analyser-report`

The alternative solution is to generate executable for each version which simplifies the usage of the tool (and end user does not require python). More information here: https://pyinstaller.org/en/stable/

### PR DESCRIPTION
**Pull request by kkazmierczyk**
Fixes #12 

This code changes project structure and allows to generate pip according to 
https://packaging.python.org/en/latest/tutorials/packaging-projects/

Once you install the package by using 
`pip install javacore_analyser-2.0rc1-py3-none-any.whl --force-reinstall`
You can run the ` javacore_analyser_batch` command.

Note: the documentation is not updated. We can create a separate task to upgrade the documentation.

The module name: `javacore_analyser`
It changes also the main file from `javacore_analyzer` to `javacore_analyser_batch` for more consistency. We can consider simplifying it to e.g. `batch`.

### CODE REVIEW

**Comment by kkazmierczyk** [comment]
What is still missing for now:
1. Create cmd for running web application
2. Upload distribution archives

**Comment by kkazmierczyk** [comment]
@PiotrAniola82 @tjanasiewicz it is ready to review. Good luck.

**Comment by PiotrAniola82** [comment]
The issue is that forward slashes are hardcoded as file path separators
in **javacore_set.py**:
    ```
def __generate_htmls_for_threads(self, output_dir, temp_dir_name):
        _create_xml_xsl_for_collection(temp_dir_name + "/threads",
                                       output_dir + "/data/xml/threads", "thread",
                                       self.threads,
                                       "thread")
        self.generate_htmls_from_xmls_xsls(self.report_xml_file,
                                           temp_dir_name + "/threads",
                                           output_dir + "/threads", )

    def __generate_htmls_for_javacores(self, output_dir, temp_dir_name):
        _create_xml_xsl_for_collection(temp_dir_name + "/javacores",
                                       output_dir + "/data/xml/javacores/", "javacore",
                                       self.javacores,
                                       "")
```

**Comment by PiotrAniola82** [comment]
@kkazmierczyk fixed the security exceptions.
All tests are passing now on Windows.
Check out my commit https://github.com/IBM/javacore-analyser/pull/37/commits/5be3c5a34973b62149e37495eacf3668eb2366be
If you're OK with it, feel free to merge

**Comment by kkazmierczyk** [comment]
@PiotrAniola82 I also made a merge and resolved the conflicts. Please check it and deliver, if you do not see the issues with this.

**Pull request merged**
